### ISSUE TITLE
compare to overmind js?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [klaudhaus/lit-up#2]

**Comment by tstewart-klaudhaus** [comment]
Hi Dzmitry, thanks for your interest in lit-up. It  is indeed a library in the same space as Overmind, but with some differences in approach and features. 

The two libraries share the approach of a one-way flow of data, as inspired by functional reactive programming patterns and made popular by libraries like Redux. Overmind has a comprehensive code modelling of some of the concepts involved, whilst lit-up opts where possible for the most streamlined approach. The core of Overmind - not counting its various tooling add-ons - is over 1600 lines of uncommented TypeScript, whilst the complete lit-up library is less than 100 lines of JavaScript including all comments. This not only means smaller page loads, but also contributes to a very straightforward API surface.

Nevertheless, lit-up still delivers considerable power, including transparent handling of sequential asynchronous update logic with clear application rendering points.

Whilst Overmind aims to be very technology agnostic and includes samples of working with frameworks like React, lit-up is design primarily for apps that use templates built with lit-html - a lightweight, efficient library from Google. This builds on the native capabilities of the web platform, such as JS template literals, ES6 modules and the DOM &lt;template&gt; tag, meaning you don't need a transpiling/bundling development toolchain, or a virtual DOM implementation, and again providing smaller download and API requirements.

Overmind has clearly had a lot of work on documentation, and that's one area where work is ongoing on lit-up. You can read an overview of the overall lit apps approach here: https://klaudhaus.com/lit-apps-intro/ but there's much more material coming soon in this space, including articles on building apps with various Web Components frameworks - the future-proof approach to UI components for the web.

I hope this is helpful, I'll close this off for now but let me know if you have any further specific questions, thanks.
